src/components/Landing/Landing.js, src/components/Link/Link.js
This PR adds a new `isExternal` prop to our `<Link>` component and updates usages on the landing page that refer to other websites.
=> Add external link support and update landing page

src/components/CourseCard/CourseCard.scss, src/components/Courses/Courses.js, src/components/Lesson/Lesson.js, src/components/Lesson/lesson.scss, src/components/LessonButton/LessonButton.js, src/components/LessonButton/LessonButton.scss, src/components/Link/Link.scss
This PR styles the lesson pages to match the styling of the rest of the site. This also includes some small style tweaks across the funnel as well. 
In order to make these changes, I changed the following things
`Lesson.js`
- Replaced divs with content sections on the Lesson.js page
- Add backlink styles to the Lesson.js 
`Courses.js`
- Change CTA to pill button form
`CourseCard.scss`
- Change relative position base to top from bottom to avoid list numbers stretching to on large contents
`LessonButton` 
- Style changes to the anchor tag to give the larger button-like appearance
=> Style lessons page

src/components/Page/Page.js, src/templates/course-template.js, src/templates/lesson-template.js, src/templates/quiz-template.js
This PR fixes a bug where content would sometimes load slightly offset from the actual top of the content.
=> Fixes page scrolling bug

content/lessons/array-methods/forEach.md, content/lessons/array-methods/map-and-filter.md, content/lessons/array-methods/reduce.md, content/lessons/array-methods/sort.md, src/components/Courses/__snapshots__/Courses.test.js.snap, src/components/LessonButton/LessonButton.js, src/components/LessonButton/LessonButton.test.js, src/templates/__snapshots__/category-template.test.js.snap, src/templates/__snapshots__/course-template.test.js.snap, src/templates/__snapshots__/index-template.test.js.snap, src/templates/__snapshots__/tag-template.test.js.snap
1. Fix lesson buttons
2. Add titles to array methods
3. Update broken snapshots
=> Add titles to array methods lessons and fix lesson button repo

package-lock.json, package.json, src/components/LessonButton/LessonButton.js
This PR adds the GA library for enhanced google tracking. We've also added outbound link tracking for tracking coverage of when a user clicks the exercises link.
=> Cooperbuilt add ga event tracking

package-lock.json, package.json, src/components/LessonButton/LessonButton.js
Testing a new GA outbound link
=> Remove unneccessary packages and add gtag outbound link

.prettierrc, src/components/Landing/Landing.js
Adds `.prettierrc` for consistency on quote style and some minor text edits on the landing page to with the goal of simplifying the language and keeping it generic.
Somewhat subjective so please read and give feedback, happy to revert any of these changes.
=> Landing text edits

.travisyml
=> Add travis yml

content/lessons/promises/advanced-promises.md, content/lessons/promises/intro-to-promises.md
WIP, waiting for the correct quiz for Intro to Promises. Using this MR to test the new Travis config.
=> Converting Promises to new Quiz format

content/courses/testing.md, content/lessons/testing/testing-workshop.md, gatsby-config.js, src/components/Lesson/Lesson.js, src/components/LessonButton/LessonButton.js, src/components/LessonButton/LessonButton.test.js, src/components/LessonButton/index.js, src/templates/lesson-template.js
This PR adds a new lesson to the testing course - the Testing Workshop.
Along with this new lesson are some changes to the structure of the lesson button.
1. Add the course description for Testing lesson 3
2. Add the lesson page for Testing lesson 3
3. Add some conditionals to the lesson page in case someone doesn't want to add pre-reads or pre-read quizzes
4. Add a primitive lesson button, which gives users the ability to add their own defined link to lesson. This gives us the flexibility to link to things other than codesandbox in our lessons.
=> Evcooper add testing workshop

content/lessons/hooks/intro-to-react-hooks.md, src/components/Lesson/Lesson.js
We got a lot of great feedback from the Hooks course. This MR will comprise some initial learnings from that, based on recurring feedback items people have mentioned.
=> Update React Hooks course based on feedback

.github/workflows/deploy.yml, .github/workflows/nodejs.yml
This MR adds a new GitHub action for continuous integration on Pull Requests!
=> Add GitHub Action for Pull Requests

README.md
Adding to the readme
Works towards the progress of #36
=> Add to the readme

src/components/Courses/Courses.js, src/templates/course-list-template.js
Signed-off-by: Johannes Siebel <johannes.siebel@gmail.com>
Added a call to the sort() method upon rendering the list of courses.
https://github.com/wayfair/awesome-learning/issues/69
=> Added sorting to courses list

gatsby/pagination/create-courses-pages.js
Fixes https://github.com/wayfair/awesome-learning/issues/63
=> Fix bug pagination courses when page in the page one

src/assets/scss/_variables.scss, src/components/Header/Header.scss
* Fix header size title on mobile 00a5756
#92
=> Fix Header Size Title on mobile

src/components/Page/Page.scss
=> Excessive space on some pages for small devices > bug fixed #72

src/components/Link/Link.scss, src/components/Page/Page.scss
=> Buttons small devices

gatsby-config.js, src/components/Header/Header.scss
* It Changes the browser color for mobile devices.
BEFORE
AFTER 
* Change theme color(same as header) 258d36e
* Remove top-border e0a5ccf
#77
=> Change theme color for mobile devices

src/components/Lesson/Lesson.js
I have removed the hyphens from the course title
Closes #78
=> Removed hyphens from course name

content/courses/Hooks.md, content/lessons/hooks/intro-to-react-hooks.md
Fix of minor typos found in `courses/Hooks.md` and `lessons/hooks/`
Continuation of auditing done in [PR #32](https://github.com/wayfair/awesome-learning-exercises/pull/32)
[Issue #30 in awesome-learning-exercises](https://github.com/wayfair/awesome-learning-exercises/issues/30)
=> fix(hooks): Fix minor typos

src/assets/scss/_base.scss, src/assets/scss/_variables.scss, src/components/Course/Content/Content.scss, src/components/Header/Header.scss, src/components/Lesson/lesson.scss, src/components/Link/Link.scss, src/components/Page/Page.scss, src/components/Quiz/quiz.scss, src/components/SectionTitle.scss, src/components/Text/Text.scss
Added a scalable font-size attribute to the Header-title class so that the logo is scaled on mobile devices
Issue #92
=> Issue #92 : Added scalable class for logo on mobile devices

src/components/Icon/Icon.test.js
Add unit tests for the Icon component
Resolves #111
=> Add Icon component unit tests

.github/workflows/nodejs.yml, package-lock.json, src/hooks/useStorage.js, src/providers/LastLessonProvider.js
This MR adds a preventative guard around the new `localStorage` hook. On server-side renders, `window.localStorage` is undefined. This MR guards against errors during our SSR step, so that builds will not be blocked.
=> Adding build step to GitHub actions, fixing LocalStorage error

src/components/Landing/TrackCard.test.js, src/components/Landing/trackCard.test.js
Added a unit test for the TrackCard component using react-testing-library. 
Resolves #113.
=> Add unit test for TrackCard component

src/components/Text/Text.test.js
Add unit tests for Text.js component in `src/components/Text/`.
Related to #120
=> Add Text tests

src/components/Page/Page.test.js
Add tests for the `Page` component:
- without title & without children
- with title & no children
- with title & with children
- without title & with children
Resolves #118
=> Add page component unit tests

src/components/Pagination/Pagination.test.js
add test for the Pagination component for these scenarios:
- Both "prev" and "next" links are present
- Only "prev" link is present
- Only "next" link is present
Resolves #119
=> Add Pagination unit tests

src/components/Carousel/Carousel.test.js, src/components/ContentSection/ContentSection.test.js
- Add unit tests for the `ContentSection` component.
- Pass ESLint -- I noticed a ESLint error in master in the existing `Carousel.test.js` script: 
I fixed this ESLint error just by importing `@testing-library/jest-dom/extend-expect` after `@testing-library/react`.
Resolves #106
=> Add unit tests for ContentSection

src/components/Lesson/Lesson.js, src/components/Lesson/Lesson.test.js, src/components/LessonButton/LessonButton.js, src/components/Link/Link.js
Written some tests for lesson.js using testing-library
Fixes #115
=> Tests for lesson.js

src/components/Header/Header.test.js
Added tests for Header and PureHeader Components.
I'm accepting any suggestions / ideas to make these tests even better, just leave your comment below 👍 
https://github.com/wayfair/awesome-learning/issues/108
=> Added tests for Header and PureHeader Components

package-lock.json
Fixes merge conflict markers in package-lock.json. It looks like those were brought in recently by https://github.com/wayfair/awesome-learning/pull/150
https://github.com/wayfair/awesome-learning/issues/154
=> fix package-lock.json conflict markers

src/components/HowTo/HowTo.test.js
Add unit test for HowTo.js. It is a static file hence wrote Unit test to ensure basic segments at at least gets rendered
Meaningful unit test coverage - HowTo #110
Meaningful unit test coverage - HowTo #110
https://github.com/wayfair/awesome-learning/issues/110
=> adding test for HowTo

src/components/Landing/Landing.js, src/components/shared/SectionTitle/SectionTitle.scss
The landing page had an incorrect heading so I am updating it to use the section title component.
Also fixed Section title xl font size variation that was broken by adding the correct font-size style
Before:
After:
=> updating the landing page to use the section title component

content/lessons/promises/advanced-promises.md
Correct the answer to Q1 for Advanced Promises
Fixes https://github.com/wayfair/awesome-learning-exercises/issues/41
=> Correct the answer to Q1 for Advanced Promises

content/courses/testing.md, content/lessons/testing/component-testing-enzyme.md, content/lessons/testing/component-testing-rtl.md
Adds React Testing Library to Testing course
=> React testing library

config.js, content/lessons/data-types/objects.md, content/lessons/hooks/intro-to-react-hooks.md, package-lock.json, package.json, src/components/shared/Layout/Layout.js, src/constants/propTypes.js, src/templates/__tests__/howTo-template.test.js, src/templates/categories-list-template.js, src/templates/category-template.js, src/templates/course-list-template.js, src/templates/course-template.js, src/templates/howTo-template.js, src/templates/index-template.js, src/templates/lesson-template.js, src/templates/not-found-template.js, src/templates/page-template.js, src/templates/quiz-template.js, src/templates/tag-template.js, src/templates/tags-list-template.js
This pull request enhances the meta/social/SEO tags used in our platform, to provide more static and contextual information on a per-page basis. Previously, a lot of this information was pretty generic and somewhat static. Now, more contextual information (based on courses/lessons/categories) will get passed to Helmet.
=> Fix Meta tags with Helmet

package-lock.json, src/assets/scss/_variables.scss
Adds global color variables that are used by the `$color--XXXXX` variables. Removes unused color variables.
Fixes #175
=> Add global color variables

.github/workflows/nodejs.yml, src/assets/scss/_variables.scss, src/assets/scss/mixins/_breakpoints.scss, src/components/Header/Header.scss, src/components/shared/Layout/Layout.scss
- Used breakpoint for XL screen sizes created from #178 
- Added CSS for Layout Page in order to center it in the page despite the screen size increasing.
Fixes #179
=> Added Max Width Margin for 1600px Screens in Layout

.storybook/config.js, src/assets/scss/_variables.scss, src/components/ClickableCard/ClickableCard.js, src/components/ClickableCard/ClickableCard.scss, src/components/ClickableCard/ClickableCard.stories.js, src/components/ClickableCard/ClickableCard.test.js, src/components/ClickableCard/README.md, src/components/ClickableCard/index.js
Adds the ClickableCard component, tests, and stories per #176.
Note that the font is not as indicated in the mockup because it seems like it has not been added across the board.
Adds #176.
=> Adds the ClickableCard component, stories, and tests.

.github/workflows/nodejs.yml, content/courses/Hooks.md, content/lessons/hooks/performance-with-hooks.md, gatsby/create-pages.js, src/components/Landing/Landing.js, src/components/Landing/Landing.test.js, src/templates/landing-template.js
* Renamed `index-template.js` and updated references to the old template name
* Removed content from `Landing.js`
Addresses #181
=> rename "index-template.js" to "landing-template.js" & remove content from Landing.js

content/lessons/data-types/types-and-equality.md
=> change link to fix dead-end for YDKJ resource

content/lessons/data-types/types-and-equality.md
Changed the link to YDKJS type and coercion section
=> Changed the link for ydkjs coercion

.eslintrc, gatsby-config.js, package-lock.json, package.json, plugins/custom-mui-theme/gatsby-browser.js, plugins/custom-mui-theme/gatsby-ssr.js, plugins/custom-mui-theme/package.json, plugins/custom-mui-theme/theme/index.js, plugins/custom-mui-theme/theme/theme.json, plugins/custom-mui-theme/wrapRootElement.js
Also sets up a custom plugin for a theme!
[Example of a custom theme here](https://github.com/dance2die/blog.custom-material-ui-gatsby-theme/blob/master/plugins/custom-mui-theme/theme/theme.json)
=> Introduce Material UI to Awesome Learning

content/lessons/solid/solid-part-1.md, content/lessons/solid/solid-part-2.md, package-lock.json
1. Correct slug paths to Solid lessons
2. Add Wikipedia article description (it was blank)
3. **Debatable** Remove 5 out of the 6 videos. Noticed they are described as "required." I think one introductory video should be sufficient since the course also teaches on its own; watching all those videos seems overwhelming.
=> Correct slug paths to Solid lessons

content/lessons/solid/solid-part-1.md
Change YouTube link to embedded version for Solid1
=> Change YouTube link to embedded version for Solid1

content/lessons/css-layouts/responsive-layouts.md
=> Typo fixes for responsive layouts course #66

.github/workflows/deploy.yml, .github/workflows/nodejs.yml, package.json
This pull request updates the minimum version of Node used by the platform.
=> Update minimum Node version

content/lessons/css-layouts/responsive-layouts.md
Fixing typo on responsive layouts course question
=> Jp fix question on css course

content/courses/Functional-Programming.md, content/lessons/functional-programming/immutability.md, src/components/Landing/LandingConstants.js
Introduces the Functional Programming course and the first lesson for it (Immutability) to the website.
=> Add functional programming course and the immutability lesson content

content/tech-talks/react-boston-2019/accessibility-in-the-age-of-components.md, content/tech-talks/react-boston-2019/dark-mode.md, content/tech-talks/react-boston-2019/enforcing-design-system-with-eslint.md, content/tech-talks/react-boston-2019/from-react-to-native.md, content/tech-talks/react-boston-2019/guided-tour-of-react-hooks.md, content/tech-talks/react-boston-2019/hooks-hocs-tradeoffs.md, content/tech-talks/react-boston-2019/internationalization.md, content/tech-talks/react-boston-2019/jest-in-strict-mode.md, content/tech-talks/react-boston-2019/layouts-in-the-component-era.md, content/tech-talks/react-boston-2019/saving-the-web.md, content/tech-talks/react-boston-2019/scalable-design-systems.md, content/tech-talks/react-boston-2019/using-react-testing-library.md, src/components/TechTalk/TechTalk.js, src/templates/tech-talk-template.js
Add links to slides to tech talks!
=> Add Slides to Tech Talks

content/courses/Functional-Programming.md, content/lessons/functional-programming/pure-functions.md
Introduces the Pure Functions lesson to the Functional Programming course.
=> Add pure functions lesson to functional programming course

content/courses/Functional-Programming.md, content/lessons/functional-programming/higher-order-functions.md
Adds the higher order functions lesson for the functional programming awesome learning course.
=> Add higher order functions lesson
